### ISSUE TITLE
UI 设计上容易找不到登录的入口，收藏单词会提示登录

### ISSUE THREAD

**Issue by JasonDevLab** [marmot-z/baicizhan-helper#12]
![WX20240905-093550](https://github.com/user-attachments/assets/603a6d57-8915-4eb5-9e85-963d229a7d1a)
如图所示，能否在弹窗处增加一个登录的入口？ 或者在插件的弹出窗口增加一个登录提示，找了好久才发现是在 option 里

**Comment by marmot-z** [comment]
好的
