### ISSUE TITLE
收藏到单词本未同步

### ISSUE THREAD

**Issue by lizhemin15** [marmot-z/baicizhan-helper#14]
浏览器端可以看到已经更新了收藏，但是手机端始终还是0个收藏的单词。请问手机端现在是否是在 我-我的收藏-单词本 查看，并没有看到单词。

**Comment by marmot-z** [comment]
有先登录并选择收藏单词的单词本嘛
![image](https://github.com/user-attachments/assets/2ec93ee1-b691-4361-8d51-71c8ca2dd156)

**Comment by lizhemin15** [comment]
> 有先登录并选择收藏单词的单词本嘛 ![image](https://private-user-images.githubusercontent.com/41913184/376097621-2ec93ee1-b691-4361-8d51-71c8ca2dd156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODk0MjAsIm5iZiI6MTcyODg4OTEyMCwicGF0aCI6Ii80MTkxMzE4NC8zNzYwOTc2MjEtMmVjOTNlZTEtYjY5MS00MzYxLThkNTEtNzFjOGNhMmRkMTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA2NTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MDJkNzEzOTQ2ZDQyY2NkNTM5MGRhZWJjMTBjNWQxMTE1OWJmYmZmNDdiMWVhODIzN2VkYTMwNTkyY2Q0ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TOtze45UXysYCobNUKStiFk0tkkAUkjK95WAllPJZxo)
有的有的
![image](https://github.com/user-attachments/assets/bedb0b45-d156-4766-9e3a-74dfbb188776)
![image](https://github.com/user-attachments/assets/6a2a79f2-cb24-4187-9920-655fc10c0916)

**Comment by marmot-z** [comment]
收藏的单词有时候不能实时同步展示在百词斩 APP 上，这个时候需要你退出 APP 重进才能看到。我这边试了下，是可以的。如果不行的话，你打开控制台看下，请求接口的响应是什么吧。

**Comment by lizhemin15** [comment]
> 收藏的单词有时候不能实时同步展示在百词斩 APP 上，这个时候需要你退出 APP 重进才能看到。我这边试了下，是可以的。如果不行的话，你打开控制台看下，请求接口的响应是什么吧。

找到原因了，一个手机号竟然能绑定多个百词斩😶，谢谢大佬

**Comment by marmot-z** [comment]
好的，不客气

**Comment by youngjuning** [comment]
用上下文的图标收藏不起作用

**Comment by marmot-z** [comment]
> 用上下文的图标收藏不起作用

“上下文的图标”是指什么？能否截图说明一下呢。
一般收藏失败可能是因为没有登录、网络抖动的原因，你可以登录或重新收藏试试

**Comment by youngjuning** [comment]
> > 用上下文的图标收藏不起作用
> 
> “上下文的图标”是指什么？能否截图说明一下呢。
> 一般收藏失败可能是因为没有登录、网络抖动的原因，你可以登录或重新收藏试试
选中单词的收藏菜单，不同的网络环境都试了

**Comment by marmot-z** [comment]
是不是插件登录的账户和手机登录的账户不是同一个

> > > 用上下文的图标收藏不起作用
> > 
> > 
> > “上下文的图标”是指什么？能否截图说明一下呢。
> > 一般收藏失败可能是因为没有登录、网络抖动的原因，你可以登录或重新收藏试试
> > 选中单词的收藏菜单，不同的网络环境都试了
