### ISSUE TITLE
感谢这个项目

### ISSUE THREAD

**Issue by vikiboss** [marmot-z/baicizhan-helper#9]
专门给你开个 issue 表示感谢，感谢你的热心开发和开源，对我真的很有帮助！

一直有类似的想法，但是不想动手，没想到你做了～

**Comment by marmot-z** [comment]
感谢支持，很高兴这个插件能对你有所帮助 XD

**Comment by akon0076** [comment]
感谢大佬，助力学习英语

**Comment by marmot-z** [comment]
> 感谢大佬，助力学习英语

😄

**Comment by joshua0x** [comment]
咨询下，这里是  登陆同步，这里是 基于 百词斩的 官方api 吗 ？

**Comment by vikiboss** [comment]
可以看看源码，应该是的

**Comment by marmot-z** [comment]
> 咨询下，这里是 登陆同步，这里是 基于 百词斩的 官方api 吗 ？

不是
